name: flutter-version-check
on:
  workflow_dispatch:

jobs:
  check-version:
    strategy:
      matrix:
        flutter-version:
          - "3.10.0"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter ${{ matrix.flutter-version }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{ matrix.flutter-version }}"
      - name: Check Flutter Version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: build apk
        run: flutter build apk --debug
        working-directory: example
